### PR TITLE
Fix link in readme

### PR DESCRIPTION
**Pull request by freemin7**

### CODE REVIEW

**Comment by LouHafer** [comment]
Turns out I somehow failed to commit a bunch of changes to README.md, including this one. Now fixed. I'm closing this pull request. Thanks for noticing --- this has been sitting in my email nagging at me to get off my butt!

**Comment by freemin7** [comment]
You are welcome

**Comment by freemin7** [comment]
You are welcome. 
Like i don't mean the nagging but that you get around to fix it.

If the you retired part is removed.
What does that mean for the current maintainership of the package?

**Comment by LouHafer** [comment]
I'm still retired, and spend most of my time these days doing woodworking / cabinetry, a long-time hobby. Happened to have a bit of down time and am catching up on various small software tasks. I'm notified of any issues with dylp, and (eventually) get around to fixing them, but as the README says, it's not under active development, so don't expect improvements. I don't expect that to change. [Clp](https://github.com/coin-or/Clp) is still used under most higher-level COIN software and is actively developed. The [HiGHs](https://github.com/coin-or/HiGHS) code is supposed to be the wave of the future but I'm unsure if there's active work to paste it into any of the other COIN solvers.

**Comment by freemin7** [comment]
The reason why i asked is that i own a rare and interesting piece of compute hardware (a NEC VectorEngine) if it turns one those could accelerate SAT/MILP with their immense memory bandwidth and double precision performance/integer performance that be very interesting and DyLP looked like the one which would compile easiest.

**Pull request closed without merging**
